### PR TITLE
PCHR-2917: Make FontAwesome icon selector more generic

### PR DESCRIPTION
**Pull request by AkA84**
## Problem
The icon element of a main menu item can have two different base classes at the moment (the why that happens is not part of the scope of this PR, i'll let @omarabuhussein take a look at it), `.crm-i` and `.fa`

wrong-markup

This made some menu items not to hide their labels when the quicksearch field was expanded, because the script that changed the markup, which in turn allowed the animation to work, could not find those items, as the `fa` class was missing

```js
function menuItemsWithFontAwesomeIcon () {
  return $('.menumain[class*="crm"]').filter(function () {
    return $('.fa', this).length > 0
  });
}
```

before

## Solution
Making the script to use a more generic css selector fixes the issue

```js
function menuItemsWithFontAwesomeIcon () {
  return $('.menumain[class*="crm"]').filter(function () {
    return $('.crm-i,.fa', this).length > 0
  });
}
```

after

## Problem
The CSS transition that happened on menu item labels when the quicksearch field was expanded was a bit "too much"

## Solution
The CSS transition was removed

no-transition

### CODE REVIEW

**Comment by jamienovick** [comment]
@AkA84 Just a quick question. I'm not sure where the decision was to remove the labels when we open the quick search but that seems a bit distracting for the user in my view. Can we live without it? Or are you just using that as the demo for the menu being responsive? Thoughts?

**Comment by jamienovick** [comment]
Also I mentioned to Rita, the new quicksearch element has a few differences to the old behaviour. I know this is the wrong place to put this but...

- If I click the search icon I should have a cursor automatically show in the search box but I don't think it does that.
- I think then the search icon should be a placeholder and should disappear I think because I don't need it anymore and its in the way? not so important if the curser appears automatically I guess. Not sure but worth looking at.
- Also the placeholder states what I'm searching (not sure if we still have that).

**Comment by AkA84** [comment]
> @AkA84 Just a quick question. I'm not sure where the decision was to remove the labels when we open the quick search but that seems a bit distracting for the user in my view

@jamienovick the decision was made between me, @mi-kon and Jon, i'd say from the start of the work on the epic, as a better alternative than making the menu sliding horizontally

**Comment by AkA84** [comment]
@jamienovick 

> If I click the search icon I should have a cursor automatically show in the search box but I don't think it does that.

Please open a bug ticket for this under PCHR-2579 and reopen the story

> I think then the search icon should be a placeholder and should disappear 

If it's not important for you, I'd avoid this as at this point we're almost done with the epic

> Also the placeholder states what I'm searching (not sure if we still have that).

I'm not sure what you mean, I didn't change the default behaviour from civicrm

**Comment by jamienovick** [comment]
1. Done.
2. yup lets drop it
3. Ok lets assume this one is fine.

thanks! It's looking really nice btw.

**Comment by jamienovick** [comment]
> @AkA84 Just a quick question. I'm not sure where the decision was to remove the labels when we open the quick search but that seems a bit distracting for the user in my view
> @jamienovick the decision was made between me, @mi-kon and Jon, i'd say from the start of the work on the epic, as a better alternative than making the menu sliding horizontally

Ok, maybe I'll take a look at this in the wild (i.e. on a dev site) but I don't think we need it and I do think its a bit distracting / too showy. Too many things changing at once. The concern Jon has was that the menu would take up more then the normal screen width when the search expanded. Can we do the hiding the labels as a responsive action. i.e. only remove the labels if the width of the screen is not available when we extend the search? I feel we are better off either showing only icons or showing icons + labels all the time really...

**Comment by AkA84** [comment]
@jamienovick i see that the transition could be a bit too much. I removed it, it feels a bit cleaner and without too much visual distraction

no-transition

**Review by deb1990 — APPROVED** [review]

**Review by deb1990 — APPROVED** [review]

**Comment by jamienovick** [comment]
Thanks @AkA84

**Pull request merged**
